### ISSUE TITLE
I have another question

### ISSUE THREAD

**Issue by yjydiancom** [ai-winter/python_motion_planning#1]
Hi, have you done any experiments to find the path by giving the map built in ros to the path planning algorithm under python?It's like feeding this map [https://github.com/ai-winter/ros_motion_planning/tree/master/src/sim_env/maps/warehouse](url) to the python version of the rrt algorithm to find the path.

**Comment by ai-winter** [comment]
Hello, @yjydiancom 

Apologies for the delayed response. I haven't conducted this experiment as it is relatively cumbersome to implement, but it is theoretically feasible.

**Comment by yjydiancom** [comment]
Okay, thanks for the reply.
