### ISSUE TITLE
在运行局部路径规划的时候怎么修改全局路径规划器？

### ISSUE THREAD

**Issue by Hangover-star** [ai-winter/python_motion_planning#16]
博主好，想请教一下运行局部路径规划的时候，如何修改全局路规划器呢，我在local_planner.py 文件中看到g_planner 的设置器 (setter) 允许通过 config 字典来设置规划器，但是我并没找到这个全局路径规划的配置字典在哪里修改。请您解答一下

**Comment by CQnancy** [comment]
> 博主好，想请教一下运行局部路径规划的时候，如何修改全局路径规划器呢，我在local_planner.py文件中看到g_planner的设置器(setter)允许通过config字典来设置规划器，但是我并没有找到这个全局路径规划的配置字典在哪里修改。请您解答一下

Did you succeed? I keep trying but failing.

**Comment by CQnancy** [comment]
> 抱歉回复迟了。`@<attribute>.setter`是 Python 中的语法糖。以下是配置示例：
> 
> from python_motion_planning.utils import Grid
> from python_motion_planning.local_planner import PID
> PID(start=(5, 5, 0), goal=(45, 25, 0), env=Grid(51, 31))
> planner.g_planner = {"planner_name": "a_star", "start": g_start, "goal": g_goal, "env": env}
> planner.run()
> 您可以在网上找到更多有关此语法糖的示例。

> from python_motion_planning.utils import Grid
> from python_motion_planning.local_planner import PID
> plt=DWA(start=(5, 5, 0), goal=(45, 25, 0), env=Grid(51, 31))
> planner.g_planner = {"planner_name": "jps", "start": g_start, "goal": g_goal, "env": env}
> planner.run()
I tried running, but it kept failing. Only the A_star algorithm and Dijkstra succeeded.

**Comment by omigeft** [comment]
> > 博主好，想请教一下运行局部路径规划的时候，如何修改全局路径规划器呢，我在local_planner.py文件中看到g_planner的设置器(setter)允许通过config字典来设置规划器，但是我并没有找到这个全局路径规划的配置字典在哪里修改。请您解答一下
> 
> Did you succeed? I keep trying but failing.

你可能是用了未完成的v2.0版本，v1.0应该没问题。之前把未完成的v2.0推到master分支上了，现在master分支改回v1.0了，再试试。
